import type { InputHTMLAttributes, Ref } from "react";

export interface InputBoxProps extends InputHTMLAttributes<HTMLInputElement> {
  /** Label text shown above input */
  label: string;
  /** Marathi / secondary label shown in muted style next to primary label */
  labelMarathi?: string;
  /** Mark field as required — shows red asterisk */
  required?: boolean;
  /** Disabled state — renders non-editable */
  disabled?: boolean;
  /** Show AUTO badge for system-generated fields */
  autoGenerated?: boolean;
  /** Error message — renders red border + message below */
  error?: string;
  /** Hint text below input */
  hint?: string;
  /** Icon on the left side of input */
  prefixIcon?: React.ReactNode;
  /** Content/element on the right side of input (e.g. unit badge) */
  suffix?: React.ReactNode;
  /** Extra class for the input element */
  inputClassName?: string;
  /** Ref forwarded to input element */
  inputRef?: Ref<HTMLInputElement>;
}

export default function InputBox({
  label,
  labelMarathi,
  required = false,
  disabled = false,
  autoGenerated = false,
  error,
  hint,
  prefixIcon,
  suffix,
  inputClassName = "",
  inputRef,
  className, // wrapper class
  ...rest
}: InputBoxProps) {
  const baseInput = [
    "w-full h-[42px] text-[13px] transition-all outline-none",
    "border rounded-[10px]",
    prefixIcon ? "pl-9 pr-3" : "px-3",
    suffix ? "pr-10" : "",
    disabled || autoGenerated
      ? "bg-[#f1f5f9] border-[var(--border)] text-[var(--text-muted)] cursor-not-allowed select-none"
      : error
      ? "bg-[#fff5f5] border-red-300 text-[var(--text-primary)] focus:border-red-400 focus:bg-white"
      : "bg-[#f8fafc] border-[var(--border)] text-[var(--text-primary)] focus:border-[var(--primary)] focus:bg-white",
    inputClassName,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div className={`flex flex-col gap-1.5 ${className ?? ""}`}>
      {/* Label row */}
      <div className="flex items-center gap-1.5">
        <label className="text-[11px] font-semibold uppercase tracking-[0.06em] text-[var(--text-secondary)]">
          {label}
        </label>
        {labelMarathi && (
          <span className="text-[11px] text-[var(--text-muted)]">({labelMarathi})</span>
        )}
        {required && <span className="text-red-500 text-[13px] leading-none">*</span>}
        {autoGenerated && (
          <span className="ml-auto text-[9px] font-bold tracking-widest px-1.5 py-0.5 rounded bg-[#e2e8f0] text-[var(--text-muted)]">
            AUTO
          </span>
        )}
      </div>

      {/* Input wrapper */}
      <div className="relative">
        {prefixIcon && (
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)] pointer-events-none">
            {prefixIcon}
          </span>
        )}

        <input
          ref={inputRef}
          disabled={disabled || autoGenerated}
          className={baseInput}
          {...rest}
        />

        {suffix && (
          <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[11px] font-semibold text-[var(--text-muted)] pointer-events-none">
            {suffix}
          </span>
        )}
      </div>

      {/* Error */}
      {error && (
        <p className="text-[11px] text-red-500 font-medium flex items-center gap-1">
          <span className="inline-block w-1 h-1 rounded-full bg-red-400 flex-shrink-0" />
          {error}
        </p>
      )}

      {/* Hint */}
      {!error && hint && (
        <p className="text-[11px] text-[var(--text-muted)]">{hint}</p>
      )}
    </div>
  );
}
